import { Platform, StyleSheet } from 'react-native';
import { premium, premiumInput, premiumLabel } from './premiumTheme';

/** Pause the screen ScrollView on Android while a dropdown is open. */
export const androidDropdownScrollLock = (dropdownOpen: boolean) =>
  Platform.OS !== 'android' || !dropdownOpen;

export const premiumStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: premium.bg,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 48,
  },
  card: {
    backgroundColor: premium.bgCard,
    borderRadius: premium.radius.xl,
    padding: 22,
    borderWidth: 1,
    borderColor: premium.border,
    marginBottom: 24,
    ...premium.shadow.card,
  },
  sectionCard: {
    backgroundColor: premium.bgCard,
    borderRadius: premium.radius.xl,
    padding: 20,
    borderWidth: 1,
    borderColor: premium.border,
    marginBottom: 20,
    overflow: 'visible',
    ...premium.shadow.card,
  },
  sectionTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: premium.primary,
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginBottom: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: premium.border,
  },
  detailRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 14,
  },
  detailLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: premium.text,
    width: 112,
  },
  detailValue: {
    fontSize: 14,
    color: '#374151',
    flex: 1,
  },
  visitedPrivacyBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    backgroundColor: '#ECFDF5',
    borderWidth: 1,
    borderColor: '#A7F3D0',
    borderRadius: premium.radius.lg,
    padding: 16,
    marginBottom: 22,
    shadowColor: '#10B981',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 18,
    elevation: 3,
  },
  visitedPrivacyIcon: {
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#10B981',
  },
  visitedPrivacyTitle: {
    fontSize: 18,
    fontWeight: '900',
    color: '#065F46',
    letterSpacing: 1,
  },
  visitedPrivacySubtitle: {
    marginTop: 3,
    fontSize: 12,
    fontWeight: '700',
    color: '#047857',
  },
  fieldWrap: {
    marginBottom: 16,
    width: '100%',
  },
  fieldWrapDropdown: {
    marginBottom: 16,
    zIndex: 1,
    overflow: 'visible',
  },
  label: {
    ...premiumLabel,
    marginBottom: 8,
  },
  input: {
    ...premiumInput,
    minHeight: 52,
    ...premium.shadow.soft,
  },
  inputMultiline: {
    ...premiumInput,
    minHeight: 120,
    textAlignVertical: 'top',
    paddingTop: 14,
    ...premium.shadow.soft,
  },
  buttonShadow: {
    ...premium.shadow.soft,
  },
  othersInput: {
    marginTop: 8,
    borderStyle: 'dashed',
    borderWidth: 1,
    borderColor: '#BFDBFE',
    borderRadius: premium.radius.md,
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#EFF6FF',
    color: premium.text,
    ...premium.shadow.soft,
  },
  dobRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    width: '100%',
  },
  dobCalendarBtn: {
    width: 52,
    minHeight: 52,
    borderWidth: 1,
    borderColor: premium.border,
    borderRadius: premium.radius.md,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: premium.bgCard,
    ...premium.shadow.soft,
  },
  tabStrip: {
    flexDirection: 'row',
    gap: 10,
    backgroundColor: '#EEF2FF',
    borderRadius: 24,
    padding: 8,
    marginBottom: 20,
  },
  tabBtn: {
    flex: 1,
    minHeight: 50,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.3)',
    alignItems: 'center',
    justifyContent: 'center',
    ...premium.shadow.soft,
  },
  tabBtnActive: {
    backgroundColor: '#2F56D9',
    borderColor: '#2F56D9',
    shadowColor: '#2F56D9',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 4,
  },
  tabBtnText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1F2937',
    letterSpacing: 0.5,
  },
  tabBtnTextActive: {
    color: '#FFFFFF',
  },
  boothAboveMapCard: {
    backgroundColor: premium.bgCard,
    borderRadius: premium.radius.xl,
    padding: 18,
    borderWidth: 1,
    borderColor: premium.border,
    marginBottom: 16,
    ...premium.shadow.card,
  },
  boothAboveMapTitle: {
    fontSize: 12,
    fontWeight: '800',
    color: premium.textMuted,
    letterSpacing: 0.8,
    marginBottom: 8,
    textTransform: 'uppercase',
  },
  boothAboveMapValue: {
    fontSize: 15,
    fontWeight: '700',
    color: premium.text,
    lineHeight: 22,
  },
  boothAboveMapAddress: {
    fontSize: 13,
    color: '#64748B',
    marginTop: 6,
    lineHeight: 20,
  },
  mapFrame: {
    height: 300,
    borderRadius: premium.radius.xl,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: premium.border,
    backgroundColor: '#EFF6FF',
    ...premium.shadow.soft,
  },
  locationBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: premium.primary,
    paddingVertical: 16,
    borderRadius: premium.radius.md,
    marginTop: 16,
    shadowColor: premium.primary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 5,
  },
  locationBtnText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
    marginLeft: 8,
  },
  actionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 28,
    gap: 12,
  },
  actionBtn: {
    flex: 1,
    height: 56,
    borderRadius: premium.radius.md,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.18,
    shadowRadius: 8,
    elevation: 4,
  },
  actionSms: {
    backgroundColor: '#2563EB',
  },
  actionWhatsapp: {
    backgroundColor: '#16A34A',
  },
  actionCall: {
    backgroundColor: '#0EA5E9',
  },
  footerRow: {
    flexDirection: 'row',
    gap: 16,
    marginBottom: 16,
  },
  secondaryBtn: {
    flex: 1,
    backgroundColor: premium.bgCard,
    borderWidth: 1,
    borderColor: premium.border,
    paddingVertical: 16,
    borderRadius: premium.radius.md,
    ...premium.shadow.soft,
  },
  secondaryBtnText: {
    textAlign: 'center',
    fontWeight: '700',
    color: premium.text,
    fontSize: 16,
  },
  primaryBtn: {
    flex: 1,
    backgroundColor: premium.primary,
    paddingVertical: 16,
    borderRadius: premium.radius.md,
    shadowColor: premium.primary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 5,
  },
  primaryBtnDisabled: {
    backgroundColor: '#94A3B8',
    shadowOpacity: 0,
    elevation: 0,
  },
  primaryBtnText: {
    textAlign: 'center',
    fontWeight: '700',
    color: '#fff',
    fontSize: 16,
  },
  updateBtn: {
    flex: 1,
    backgroundColor: '#16A34A',
    paddingVertical: 16,
    borderRadius: premium.radius.md,
    shadowColor: '#16A34A',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 5,
  },
  updateBtnDisabled: {
    backgroundColor: '#9CA3AF',
    shadowOpacity: 0,
    elevation: 0,
  },
  updateBtnText: {
    textAlign: 'center',
    fontWeight: '700',
    color: '#fff',
    fontSize: 16,
  },
  statPillTotal: {
    backgroundColor: '#EEF2FF',
    borderColor: '#C7D2FE',
  },
  statPillTotalText: {
    color: '#3730A3',
  },
  statPillMale: {
    backgroundColor: '#E0F2FE',
    borderColor: '#7DD3FC',
  },
  statPillMaleText: {
    color: '#075985',
  },
  statPillFemale: {
    backgroundColor: '#FCE7F3',
    borderColor: '#F9A8D4',
  },
  statPillFemaleText: {
    color: '#9D174D',
  },
  printBtn: {
    backgroundColor: '#64748B',
    paddingVertical: 20,
    borderRadius: premium.radius.md,
    marginBottom: 48,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
  },
  printBtnText: {
    textAlign: 'center',
    fontWeight: '700',
    color: '#fff',
    fontSize: 16,
  },
  formCard: {
    backgroundColor: premium.bgCard,
    borderRadius: premium.radius.xl,
    padding: 22,
    borderWidth: 1,
    borderColor: premium.border,
    marginBottom: 16,
    ...premium.shadow.card,
  },
  searchInputWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    borderRadius: premium.radius.lg,
    paddingHorizontal: 16,
    height: 56,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: premium.border,
    ...premium.shadow.soft,
  },
  searchInput: {
    flex: 1,
    marginLeft: 12,
    fontSize: 16,
    fontWeight: '600',
    color: premium.text,
  },
  boothCard: {
    backgroundColor: premium.bgCard,
    borderRadius: premium.radius.lg,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: premium.border,
    ...premium.shadow.soft,
  },
});
